name: snake

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate snake
        uses: Platane/snk@v1
        with:
          github_user_name: joaolopes45   # seu usuário GitHub
          svg_out_path: ./github-contribution-grid-snake.svg
