name: snake

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # roda a cada hora, opcional

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate snake
        uses: Platane/snk@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./github-contribution-grid-snake.svg
